### ISSUE TITLE
[Bug] Regarding the issue of console content not matching the actual log content caused by `misc.secure-seed` error

### ISSUE THREAD

**Issue by liangcha385** [Dreeam-qwq/Leaf#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

After the project changes, the old world will still be used, and the console will not generate any prompts or errors, only force the server to shut down
Related errors will only be displayed when you view the log file

### Expected behaviour

The console content should match the actual log content

### To Reproduce

1. Shut down the server to ensure that the world is saved normally
2. Change `misc.secure-seed`
3. Restart the server and wait for a moment. You will see that the server suddenly terminates without any relevant reminders unless you check the log files

### Plugin list

[23:55:54 INFO]: Paper Plugins: (4):
[23:55:54 INFO]:  - FancyHolograms, FancyNpcs, HuskSync, SignedVelocity
[23:55:54 INFO]: Bukkit Plugins: (12):
[23:55:54 INFO]:  - Craftorithm, DeluxeMenus, LuckPerms, MythicMobs, PAPIProxyBridge, PlaceholderAPI, TAB-Bridge, Vault, WorldEdit, WorldGuard
[23:55:54 INFO]:  XConomy, ZAutoBroadcast

### Leaf Version

1.21-DEV-ver/1.21@ee6983a (2024-08-11T10:32:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Error log (if applicable)

https://mclo.gs/h1nVNL4

**Comment by Dreeam-qwq** [comment]
Can't replicate.
Please read comments of secure seed config
```
WARNING! You need to backup your server and prepare a new world if you want to enable it, at least for now.
```

---

- If the world already generated and the secure-seed is disabled, then you enable the secure-seed and run the server, the server will crash and the error can show both on console and in the log
- If the world already generated and the secure-seed is enabled, then you disable the secure-seed in config and run the server, the server will not crash and run normally, but you can't enable the secure-seed again, since you need to prepare new world to enable the secure seed.

**Comment by Dreeam-qwq** [comment]
Try https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.21.1

**Comment by Dreeam-qwq** [comment]
Try latest Leaf 1.21.1 to see if this issue still happens
