### ISSUE TITLE
Server on Java 23 and above crash with spark enabled

### ISSUE THREAD

**Issue by NogradThGin** [Dreeam-qwq/Leaf#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

The server crash when using a java version above 22. GraalVM, Azul or classical Java.

Crash occurs when a player join the server with spark background profiler enabled.
You can generate the map with Chunky (did it for 16 mins) as long no player is on the server.

### Expected behaviour

No crash when running the server with players.

Actually the argument « -DPurpur.IReallyDontWantSpark=true » doesn't disable Spark.

### To Reproduce

Download a 23 or 24 java version.
Start the server.
Join the server.

### Plugin list

Spark (enabled)
bStats (disabled)
Chunky
Pl3xmap
Minecraft Prometheus Exporter

### Leaf Version

1.21.1

### Error log (if applicable)

https://mclo.gs/10IuH0r

### Configuration

https://mclo.gs/2oE919l

**Comment by HaHaWTH** [comment]
Is it reproducible on Purpur?
btw you can disable bundled spark here: https://docs.papermc.io/paper/reference/global-configuration#spark_enabled

**Comment by NogradThGin** [comment]
Yes same behavior on Purpur (java 24 GraalVM EA)

**Comment by Dreeam-qwq** [comment]
Spark uses async-profiler for profilering on linux machine. And this crash is a async-profiler issue, referring to related issue https://github.com/async-profiler/async-profiler/issues/923, which is already fixed in async-profiler v3.0+. However, Spark uses async-profiler v2.8.3 for now. There is an existing WIP pr in spark for upgrading async-profiler to 3.0, see https://github.com/lucko/spark/pull/386, but according to lucko's comment, it may not be done very soon.

You can try to disable bundled spark by disabling it in paper config (like @HaHaWTH mentioned above), or switch to Java 21 or 22.

**Comment by NogradThGin** [comment]
OK thanks for the update and explanations!
I close the issue as it's not related to Leaf.
